# -*- coding: utf-8 -*-
"""attendance_analytics_ststem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTLTohm2HxI4zIaksiLo96KAXKmabAJR
"""

#cell 01
#Display Main Menu
def display_menu():
    print(" Attendance System ")
    print("1. Record Attendance")
    print("2. View attendance Summary")
    print("3. Exit")

#Cell 02
#Collect Classroom Information
def get_class_information():
    class_name = input("Enter Class Name : ")
    subject_name = input("Enter Subject Name : ")
    total_students = int(input("Enter Total Students : "))

    return class_name, subject_name, total_students

#cell 03
#Record Attendance
def record_attendance(total_students):
    present = 0
    absent = 0

    for i in range(total_students):
        status = input(f"Student {i+1}: ").upper()

        while status != "P" and status != "A":
            print("Invalid Attendance")
            status = input(f"Student {i+1}: ").upper()

        if status == "P":
            present += 1
        else:
            absent += 1

    return present, absent

#Cell 04
#Calculate Attendance Status
def calculate_attendance(present, total):
    percentage = (present / total) * 100

    if percentage >= 90:
        status = "Excellent"
    elif percentage >= 75:
        status = "Good"
    else:
        status = "Poor"

    return percentage, status

#Cell 05
#Generate Attendance Report
def display_report(class_name, subject_name, total, present, absent, percentage, status):

    print("\nAttendance Report")
    print("-------------------------")
    print("Class Name:", class_name)
    print("Subject:", subject_name)
    print("Total Students:", total)
    print("Present Students:", present)
    print("Absent Students:", absent)
    print("Attendance:", round(percentage, 2), "%")
    print("Status:", status)

    print("\nChart")
    print("Present:", "*" * present)
    print("Absent :", "*" * absent)

#Cell 06
def main():

    while True:

        display_menu()

        choice = input("Enter Choice : ")

        if choice == "1":

            class_name, subject_name, total_students = get_class_information()

            present, absent = record_attendance(total_students)

            percentage, status = calculate_attendance(present, total_students)

            display_report(
                class_name,
                subject_name,
                total_students,
                present,
                absent,
                percentage,
                status
            )

            record = {
                "class": class_name,
                "subject": subject_name,
                "percentage": percentage
            }

            attendance_records.append(record)

            back = input("Would you like to return to the main menu? (Y/N) : ").upper()

            if back == "Y":
                continue
            else:
                print("Classes Processed :", len(attendance_records))
                print("Program Ended")
                break

        elif choice == "2":

            if len(attendance_records) == 0:
                print("No Record Found")

            else:
                print()
                print("Attendance Summary")

                for data in attendance_records:
                    print(data["class"], "-", data["subject"], "-", "{:.2f}%".format(data["percentage"]))

        elif choice == "3":

            print("Classes Processed :", len(attendance_records))
            print("Program Ended")
            break

        else:
            print("Invalid Choice")

#Cell 08
#Challenge 01
def attendance_chart(present, absent):
    print("Present :", "*" * present)
    print("Absent  :", "*" * absent)

#Cell 09
#Challenge 02
attendance_records = []

#Cell 10
main()